name: bot

on:
  push:
    branches:
      - master

jobs:
  bot:
    runs-on: ubuntu-latest
    environment: bot
    steps:
      - name: deploy
      env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}